#!/usr/bin/env bash
# Bridges Terraform outputs into a Helmfile values file, so nobody
# hand-copies IAM role ARNs / cluster info between the two. Run this
# after `terraform apply` (or whenever those outputs might have changed)
# and before any `helmfile` command.
#
# Usage: scripts/generate-terraform-values.sh <dev|staging|prod>
set -euo pipefail

ENV="${1:?usage: $0 <dev|staging|prod>}"
HELM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$HELM_DIR/../terraform/live"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required (brew install jq)" >&2
  exit 1
fi

(cd "$TF_DIR" && terraform workspace select "$ENV")
OUTPUTS_JSON="$(cd "$TF_DIR" && terraform output -json)"

VALUES_JSON="$(jq -c '
  {
    clusterName:              .eks_cluster_name.value,
    vpcId:                    .vpc_id.value,
    lbControllerRoleArn:      .eks_lb_controller_role_arn.value,
    externalSecretsRoleArn:   .eks_external_secrets_role_arn.value,
    clusterAutoscalerRoleArn: .eks_cluster_autoscaler_role_arn.value,
    ecrBackendRepositoryUrl:  .ecr_backend_repository_url.value,
    ecrFrontendRepositoryUrl: .ecr_frontend_repository_url.value,
    rdsSecretArn:             .rds_master_user_secret_arn.value,
    rdsEndpoint:              .rds_endpoint.value,
    rdsDatabaseName:          .rds_database_name.value,
    redisEndpoint:            .redis_endpoint.value
  }
' <<<"$OUTPUTS_JSON")"

# Fail loudly here, not three layers downstream as a confusing
# ImagePullBackOff/InvalidImageName once a Helm chart renders one of
# these straight into an image reference. jq resolves a field this
# script asks for but terraform output doesn't have (a typo above, an
# output renamed in terraform/live/outputs.tf, or this file predating an
# output that's since been added) to `null` with no error at all - and
# `tostring | @json` used to turn that into the literal four-character
# string "null", which then rendered as an actual YAML null wherever a
# Helm chart's values.yaml.gotmpl referenced it. Found live exactly that
# way: ecrFrontendRepositoryUrl had been "null" since before
# ecr_frontend_repository_url existed as a Terraform output, silently,
# until a bare `helmfile apply` (bypassing CI, which always regenerates
# this file fresh) actually deployed it and the frontend pod came up
# with an empty image reference.
MISSING="$(jq -r 'to_entries | map(select(.value == null)) | map(.key) | join(", ")' <<<"$VALUES_JSON")"
if [[ -n "$MISSING" ]]; then
  echo "generate-terraform-values.sh: these terraform outputs are missing/null: $MISSING" >&2
  echo "Check that terraform/live/outputs.tf and this script's jq mapping still agree, then re-run." >&2
  exit 1
fi

OUT_FILE="$HELM_DIR/${ENV}.generated.yaml"

{
  echo "# Generated by scripts/generate-terraform-values.sh - do not hand-edit."
  echo "# Source of truth is \`terraform output\` in terraform/live, workspace ${ENV}."
  jq -r '
    to_entries
    | map("\(.key): \(.value | tostring | @json)")
    | join("\n")
  ' <<<"$VALUES_JSON"
} >"$OUT_FILE"

echo "Wrote $OUT_FILE"
