#!/usr/bin/env bash
# Bridges Terraform outputs into a Helmfile values file, so nobody
# hand-copies IAM role ARNs / cluster info between the two. Run this
# after `terraform apply` (or whenever those outputs might have changed)
# and before any `helmfile` command.
#
# Usage: scripts/generate-terraform-values.sh <dev|staging|prod>
set -euo pipefail

ENV="${1:?usage: $0 <dev|staging|prod>}"
HELM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$HELM_DIR/../terraform/live"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required (brew install jq)" >&2
  exit 1
fi

(cd "$TF_DIR" && terraform workspace select "$ENV")
OUTPUTS_JSON="$(cd "$TF_DIR" && terraform output -json)"

OUT_FILE="$HELM_DIR/${ENV}.generated.yaml"

{
  echo "# Generated by scripts/generate-terraform-values.sh - do not hand-edit."
  echo "# Source of truth is \`terraform output\` in terraform/live, workspace ${ENV}."
  jq -r '
    {
      clusterName:              .eks_cluster_name.value,
      vpcId:                    .vpc_id.value,
      lbControllerRoleArn:      .eks_lb_controller_role_arn.value,
      externalSecretsRoleArn:   .eks_external_secrets_role_arn.value,
      clusterAutoscalerRoleArn: .eks_cluster_autoscaler_role_arn.value,
      ecrBackendRepositoryUrl:  .ecr_backend_repository_url.value,
      rdsSecretArn:             .rds_master_user_secret_arn.value,
      rdsEndpoint:              .rds_endpoint.value,
      rdsDatabaseName:          .rds_database_name.value,
      redisEndpoint:            .redis_endpoint.value,
      frontendOrigin:           "https://\(.frontend_distribution_domain_name.value)"
    }
    | to_entries
    | map("\(.key): \(.value | tostring | @json)")
    | join("\n")
  ' <<<"$OUTPUTS_JSON"
} >"$OUT_FILE"

echo "Wrote $OUT_FILE"
